# Generated by Django 5.2.1 on 2025-05-14 06:35

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('math_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mathquery',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mathquery',
            name='question',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='mathquery',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='math_api.appuser'),
        ),
    ]
